version: '3.8'

services:
  db:
    image: postgres:15
    container_name: movieflix_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movieflix
    ports:
      - "5432:5432"
    volumes:
      - movieflix_data:/var/lib/postgresql/data
    networks:
      - movieflix-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  movieflix_data:

networks:
  movieflix-net:
    driver: bridge