spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movieflix
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration


server:
  port: 8080


movieflix:
    security:
      secret: "JDNASFAS54F41681"